name: Construir y Publicar imagen Docker

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir la imagen Docker
        run: docker build -t ${{ secrets.DOCKER_USER }}/uunivalle:latest .

      - name: Publicar la imagen Docker
        run: docker push ${{ secrets.DOCKER_USER }}/uunivalle:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código (docker-compose.yml, setup_vm.sh)
        uses: actions/checkout@v5

      # 1️⃣ Configurar acceso SSH
      - name: Configurar agente SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 2️⃣ Copiar script de configuración a la VM
      - name: Copiar script de configuración a la VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "setup_vm.sh"
          target: "/tmp/"

      # 3️⃣ Ejecutar script de instalación en la VM (instala docker si es necesario)
      - name: Ejecutar script de instalación en la VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            chmod +x /tmp/setup_vm.sh
            /tmp/setup_vm.sh
            rm /tmp/setup_vm.sh  # eliminar script por seguridad

      # 4️⃣ Copiar docker-compose.yml a la VM
      - name: Copiar docker-compose.yml a la VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/home/${{ secrets.SSH_USER }}/deploy/"

      # 5️⃣ Ejecutar docker-compose en la VM
      - name: Ejecutar docker-compose en la VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            DEPLOY_PATH="/home/${{ secrets.SSH_USER }}/deploy"
            cd $DEPLOY_PATH

            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
            
            docker-compose pull
            docker-compose up -d --force-recreate
            docker logout
